# Generated by Django 2.2.5 on 2019-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191119_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='static/avatars/default.png', upload_to='static/', verbose_name='头像'),
        ),
    ]
