# Generated by Django 2.2.5 on 2019-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191120_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='static/avatars/default.png', upload_to='static/avatars/', verbose_name='头像'),
        ),
    ]
