# Generated by Django 2.2.5 on 2019-11-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191120_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息表User', 'verbose_name_plural': '用户信息表User'},
        ),
    ]
