# Generated by Django 2.2.5 on 2019-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('F5', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='F5')),
                ('network_ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='内网IP')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('platform', models.CharField(choices=[('移动查勘', '移动查勘'), ('移动协赔', '移动协赔'), ('华为云', '华为云'), ('小微', '小微'), ('流程控制平台', '流程控制平台'), ('其他', '其他')], max_length=128, verbose_name='项目组')),
                ('region', models.CharField(choices=[('香港', '香港'), ('东京', '东京'), ('华北2', '华北2'), ('佛山', '南中心'), ('其他', '其他')], max_length=128, verbose_name='机房位置')),
                ('weblogic', models.CharField(choices=[('主管', '主管'), ('受管', '受管')], max_length=128, verbose_name='服务类别')),
                ('weblogic_port', models.IntegerField(blank=True, null=True, verbose_name='服务端口')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('port', models.IntegerField(blank=True, default='22', null=True, verbose_name='登录端口')),
                ('is_active', models.BooleanField(default=True, verbose_name='服务状态')),
                ('name_war', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务名称')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
