# Generated by Django 2.1.4 on 2019-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbinfo',
            name='domains',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='域路径'),
        ),
    ]
