# Generated by Django 2.1.4 on 2019-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_cmdbinfo_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdbinfo',
            name='weblogic',
        ),
        migrations.RemoveField(
            model_name='cmdbinfo',
            name='weblogic_port',
        ),
        migrations.AlterField(
            model_name='cmdbinfo',
            name='name_war',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目包路径'),
        ),
    ]
