# Generated by Django 2.2.5 on 2019-11-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章Article', 'verbose_name_plural': '文章Article'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name': '文章-标签Article2Tag', 'verbose_name_plural': '文章-标签Article2Tag'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name': '文章详情ArticleDetail', 'verbose_name_plural': '文章详情ArticleDetail'},
        ),
        migrations.AlterModelOptions(
            name='articleupdown',
            options={'verbose_name': '文章点赞ArticleUpDown', 'verbose_name_plural': '文章点赞ArticleUpDown'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '站点BLOG', 'verbose_name_plural': '站点BLOG'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类Category', 'verbose_name_plural': '文章分类Category'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论Comment', 'verbose_name_plural': '评论Comment'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签Tag', 'verbose_name_plural': '标签Tag'},
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.CharField(max_length=32, unique=True, verbose_name='个人博客后缀'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=32, verbose_name='博客主题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=64, verbose_name='个人博客标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, verbose_name='分类标题'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标签名'),
        ),
    ]
